"""AI service for interacting with multiple LLM providers and generating summaries."""
import httpx
import json
import os
from typing import Optional

LEARNING_SYSTEM_PROMPT = """You are a learning assistant. The student is working on an academic assignment. 
Never give direct answers, solutions, or complete code. 
Instead, explain the underlying concept, ask guiding questions, and help the student arrive at the answer themselves. 
If they ask you to write code, explain the approach and let them write it.
Be encouraging and supportive while maintaining academic integrity."""

ANALYSIS_SYSTEM_PROMPT = """You are an academic integrity analyst for EduTrace, an educational transparency platform. 
You will be given evidence about a student's work session including:
1. The student's final submission content
2. Every AI prompt they sent during the session  
3. Every AI response they received
4. Keystroke statistics including paste events, typing patterns, and content snapshots

Provide a structured analysis in the following format:

## AI Contribution Assessment
**Level**: [Low / Medium / High]

## Evidence Summary
[Summarize key evidence points]

## Detailed Analysis
### Sections with Likely AI Influence
[List specific sections and why you believe AI influenced them]

### Evidence of Independent Work
[Highlight areas showing original student effort]

### Paste Events Analysis
[Analyze any significant paste events — large pastes may indicate copying from outside the app]

## Typing Pattern Analysis
[Comment on typing speed, consistency, and any anomalies]

## Recommendations
[Fair, evidence-based recommendations for the professor]

## Confidence Level
[How confident you are in this assessment and what uncertainties exist]

Be fair, evidence-based, and acknowledge uncertainty where it exists. Remember: your role is to present evidence, not to accuse."""

CHAT_SYSTEM_PROMPT = """You are an academic integrity analyst assistant. A professor is asking follow-up questions about an AI usage analysis you previously generated for a student submission.

You have access to:
1. The original analysis summary
2. The full evidence (submission content, AI interactions, keystroke data)
3. The conversation history

Answer the professor's questions with specific, evidence-grounded responses. Cite specific parts of the evidence when possible. Be honest about limitations and uncertainty."""

EXTERNAL_DETECTOR_PROMPT = """You are an advanced AI detection model suite, functioning like ZeroGPT, Copyleaks, and Turnitin. 
Analyze the provided text and determine the probability that it was generated by an AI.
Evaluate perplexity, burstiness, syntax patterns, and predictability.
Return ONLY a valid JSON object in this exact format (no markdown tags, just the raw JSON object):
{
  "zerogpt": {"score": 85, "reason": "Consistent perplexity suggests AI influence."},
  "copyleaks": {"score": 92, "reason": "Stylistic patterns closely match common LLM outputs."},
  "gptzero": {"score": 78, "reason": "Low burstiness detected throughout the text."}
}"""


async def call_ai_provider(
    provider: str,
    api_key: str,
    prompt: str,
    system_prompt: str = LEARNING_SYSTEM_PROMPT,
) -> str:
    """Route AI calls to the appropriate provider."""
    try:
        if provider == "openai":
            return await _call_openai(api_key, prompt, system_prompt)
        elif provider == "anthropic":
            return await _call_anthropic(api_key, prompt, system_prompt)
        elif provider == "gemini":
            return await _call_gemini(api_key, prompt, system_prompt)
        elif provider == "openrouter":
            return await _call_openrouter(api_key, prompt, system_prompt)
        else:
            return f"Error: Unknown provider '{provider}'"
    except Exception as e:
        return f"Error calling {provider}: {str(e)}"


async def _call_openai(api_key: str, prompt: str, system_prompt: str) -> str:
    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.openai.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": "gpt-4o-mini",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 2048,
                "temperature": 0.7,
            },
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]


async def _call_anthropic(api_key: str, prompt: str, system_prompt: str) -> str:
    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 2048,
                "system": system_prompt,
                "messages": [
                    {"role": "user", "content": prompt},
                ],
            },
        )
        response.raise_for_status()
        data = response.json()
        return data["content"][0]["text"]


async def _call_gemini(api_key: str, prompt: str, system_prompt: str) -> str:
    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={api_key}",
            headers={"Content-Type": "application/json"},
            json={
                "system_instruction": {
                    "parts": [{"text": system_prompt}]
                },
                "contents": [
                    {
                        "parts": [{"text": prompt}]
                    }
                ],
                "generationConfig": {
                    "maxOutputTokens": 2048,
                    "temperature": 0.7,
                },
            },
        )
        response.raise_for_status()
        data = response.json()
        return data["candidates"][0]["content"]["parts"][0]["text"]


async def _call_openrouter(api_key: str, prompt: str, system_prompt: str) -> str:
    async with httpx.AsyncClient(timeout=60.0) as client:
        response = await client.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": "google/gemini-2.0-flash-001",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 2048,
                "temperature": 0.7,
            },
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]


async def generate_ai_summary(
    final_content: str,
    ai_interactions: list,
    keystroke_stats: dict,
    api_key: str,
) -> dict:
    """Generate an AI usage summary using OpenRouter."""
    # Build the evidence payload
    interactions_text = ""
    for i, interaction in enumerate(ai_interactions, 1):
        interactions_text += f"\n--- Interaction {i} ---\n"
        interactions_text += f"Provider: {interaction['provider']}\n"
        interactions_text += f"Student Prompt: {interaction['student_prompt']}\n"
        interactions_text += f"AI Response: {interaction['model_response'][:500]}...\n"

    evidence = f"""
## Final Submission Content
{final_content[:3000]}

## AI Interactions ({len(ai_interactions)} total)
{interactions_text if interactions_text else "No AI interactions recorded."}

## Keystroke Statistics
- Total keystrokes: {keystroke_stats.get('total_keystrokes', 0)}
- Paste events: {keystroke_stats.get('paste_events', 0)}
- Total characters pasted: {keystroke_stats.get('total_chars_pasted', 0)}
- Content snapshots taken: {keystroke_stats.get('snapshots', 0)}
- Typing sessions: {keystroke_stats.get('typing_sessions', 0)}
- Average characters per minute: {keystroke_stats.get('avg_chars_per_min', 'N/A')}
"""

    summary = await _call_openrouter(
        api_key,
        evidence,
        ANALYSIS_SYSTEM_PROMPT,
    )

    # Try to extract contribution level
    level = "medium"
    lower_summary = summary.lower()
    if "**level**: low" in lower_summary:
        level = "low"
    elif "**level**: high" in lower_summary:
        level = "high"

    return {
        "summary": summary,
        "contribution_level": level,
    }


async def chat_with_summary(
    summary_text: str,
    evidence_context: str,
    chat_history: list,
    professor_message: str,
    api_key: str,
) -> str:
    """Chat about a specific summary."""
    prompt = f"""
Summary:
{summary_text}

## Evidence Context
{evidence_context[:2000]}

## Conversation History
{history_text}

## Professor's Question
{professor_message}

Please answer the professor's question based on the evidence and your previous analysis.
"""
    return await call_ai_provider("openrouter", api_key, prompt, CHAT_SYSTEM_PROMPT)

async def run_external_ai_scan(text: str, api_key: str) -> str:
    return await call_ai_provider("openrouter", api_key, text, EXTERNAL_DETECTOR_PROMPT)
